version: '2'
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      - storm
#    restart: always

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 6627:6627
    networks:
      - storm
      - loggingaggregation_elk
    volumes:
      - ./log4j2:/apache-storm-1.1.0/log4j2
      - ./lib:/apache-storm-1.1.0/lib

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    networks:
      - storm
      - loggingaggregation_elk
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    volumes:
      - ./log4j2:/apache-storm-1.1.0/log4j2
      - ./lib:/apache-storm-1.1.0/lib

  ui:
    image: storm
    container_name: storm-ui
    command: storm ui
    ports:
      - 8080:8080
    networks:
      - storm
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper

networks:

  storm:
    driver: bridge
  loggingaggregation_elk:
      external: true